### PR TITLE
Fix indentation in descriptions XML

### PR DESCRIPTION
**Pull request by HedwigAR**
Prettier was changing indentation on descriptions in xml files, this was leading to odd indentation in Studio pro.

### CODE REVIEW

**Review by rahmanunver — APPROVED** [review]

**Review by iobuhov — CHANGES_REQUESTED** [review]
Let's not ignore XML

**Comment by iobuhov** [comment]
We should not disable prettier for source files, and XML one of those. I'll show you how to fix prettier config, so it not wrap text lines.

**Comment by iobuhov** [comment]
Here is what you need.
```js
const base = require("@mendix/pluggable-widgets-tools/configs/prettier.base.json");
module.exports = {
    ...base,
    xmlSelfClosingSpace: true,
    xmlWhitespaceSensitivity: "ignore",
    plugins: ["@prettier/plugin-xml"],
    overrides: [
        {
            files: "*.xml",
            options: {
                printWidth: 500
            }
        }
    ]
};
```

Also, you need `@prettier/plugin-xml`. I took this settings from [prettier config for web-widgets](https://github.com/mendix/web-widgets/blob/main/packages/shared/prettier-config-web-widgets/index.js)

I think I'll include this settings in PWT soon.

**Review by iobuhov — APPROVED** [review]
Well done 👏 , you can be  proud of yourself 💪

**Pull request merged**
